FROM docker.elastic.co/kibana/kibana:7.3.0
ADD kibana.yml /usr/share/kibana/config/
#COPY --chown=kibana:kibana kibana.yml /usr/share/kibana/config/kibana.yml
#/kibana.yml:/usr/share/kibana/config/kibana.yml